### ISSUE TITLE
Add example for "hostname" in remote db

### ISSUE THREAD

**Issue by josefglatz** [webdevops/go-sync#14]

**Comment by mediaessenz** [comment]
Currently it seems, that the parameter "hostname" will be ignored.

As a workaround you can do this:
```yaml
options:
  mysql:
    - "-h mysql"
  mysqldump:
    - "-h mysql"
```
